[package]
name = "boundary-check"
version = "0.1.0"
authors = ["njulzb <hellolizebin@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.release]
opt-level = 0

[profile.dev]
opt-level = 0
